# Generated by Django 3.1.4 on 2020-12-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_change_date', models.DateField(auto_now_add=True)),
                ('time_stamp', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField()),
                ('water_change_interval', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
